### PR TITLE
#3 testing rultor and pdd

### PR DESCRIPTION
**Pull request by ammaratef45**
PR for #3

### CODE REVIEW

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) please review this and merge or reject

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by ammaratef45** [comment]
@rultor stop

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by ammaratef45** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance-api#9` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
